# GitHub Sponsorsの設定
# プロジェクトをサポートしたいユーザー向けの設定ファイル

# GitHub Sponsors
# github: [skdhc592]

# その他のスポンサープラットフォーム
# patreon: username
# ko_fi: username
# custom: ['https://www.paypal.me/username', 'https://example.com']
